# Site settings
title: A record for knowledge acquired during post-graduate
SEOTitle: Selene Ru的知识整理 | Blog
header-img: img/home-bg.jpg
email: rimingselene@gmail.com  # 请替换为你的邮箱
description: "这里是Selene Ru的个人博客，记录我研究生期间的知识管理与学习过程"
keyword: "Selene Ru, 研究生, 知识管理, 计量经济学, 凸分析, 机器学习, 博客, 课程, 学习"
url: "https://yourwebsite.com"  # 请替换为你的主机地址
baseurl: ""  # 如果你的博客在子目录中，修改为 "/blog"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: SeleneRu

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
timezone: CN

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: seleneru

# Analytics settings
ga_track_id: "UA-xxxxxxxx-x"  # 请替换为你的Google Analytics ID
ga_domain: yourwebsite.com

# Sidebar settings
sidebar: true
sidebar-about-description: "研究生期间的学习与知识管理，记录个人成长与探索"
sidebar-avatar: https://github.com/SeleneRu.png  # 请替换为你的头像链接

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false

# Courses
courses:
  [
    { title: "计量经济学", href: "/courses/microeconomics" },
    { title: "凸分析", href: "/courses/convex-analysis" },
    { title: "机器学习", href: "/courses/machine-learning" },
  ]
